# render.yml - Configuração de deploy para Render
services:
  - type: web
    name: sushiweb-backend
    runtime: node
    plan: free  # Plano gratuito (pode ser alterado para starter, standard, pro)
    region: oregon  # Região do servidor (oregon, frankfurt, singapore)
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    # Configurações de auto-deploy
    branch: main  # Branch que será monitorada para deploy automático
    
    # Headers de segurança
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=()
    
    # Configurações de build
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - nest-cli.json
      ignoredPaths:
        - README.md
        - .gitignore
        - docs/**
        - tests/**
        - "*.test.ts"
        - "*.spec.ts"
